# Generated by Django 6.1 on 2026-08-10 10:51

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lsaprofile',
            index=django.contrib.postgres.indexes.GinIndex(fields=['skills'], name='lsa_skills_gin_idx'),
        ),
    ]
